"""Create user_news_scores table

Revision ID: e3afbf4abd54
Revises: e612a307b18e
Create Date: 2025-11-13 18:05:49.047150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3afbf4abd54'
down_revision: Union[str, Sequence[str], None] = 'e612a307b18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_news_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'news_id', name='unique_user_news_score')
    )
    op.create_index('idx_user_score', 'user_news_scores', ['user_id', 'score'], unique=False)
    op.create_index(op.f('ix_user_news_scores_news_id'), 'user_news_scores', ['news_id'], unique=False)
    op.create_index(op.f('ix_user_news_scores_score'), 'user_news_scores', ['score'], unique=False)
    op.create_index(op.f('ix_user_news_scores_user_id'), 'user_news_scores', ['user_id'], unique=False)
    op.create_index('idx_news_category_created', 'news', ['category', 'created_at'], unique=False)
    op.create_index('idx_news_created_at', 'news', ['created_at'], unique=False)
    op.create_index('idx_category_weight_user', 'user_category_weights', ['user_id'], unique=False)
    op.create_index('idx_interaction_user_news', 'user_interactions', ['user_id', 'news_id'], unique=False)
    op.create_index('idx_interaction_user_shown', 'user_interactions', ['user_id', 'shown_at'], unique=False)
    op.drop_constraint(op.f('users_max_id_key'), 'users', type_='unique')
    op.create_index('idx_user_last_active', 'users', ['last_active'], unique=False)
    op.create_index(op.f('ix_users_max_id'), 'users', ['max_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_max_id'), table_name='users')
    op.drop_index('idx_user_last_active', table_name='users')
    op.create_unique_constraint(op.f('users_max_id_key'), 'users', ['max_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_interaction_user_shown', table_name='user_interactions')
    op.drop_index('idx_interaction_user_news', table_name='user_interactions')
    op.drop_index('idx_category_weight_user', table_name='user_category_weights')
    op.drop_index('idx_news_created_at', table_name='news')
    op.drop_index('idx_news_category_created', table_name='news')
    op.drop_index(op.f('ix_user_news_scores_user_id'), table_name='user_news_scores')
    op.drop_index(op.f('ix_user_news_scores_score'), table_name='user_news_scores')
    op.drop_index(op.f('ix_user_news_scores_news_id'), table_name='user_news_scores')
    op.drop_index('idx_user_score', table_name='user_news_scores')
    op.drop_table('user_news_scores')
    # ### end Alembic commands ###
