"""add ondelete cascade to users FKs

Revision ID: e612a307b18e
Revises: f16941095184
Create Date: 2025-11-08 15:46:29.286816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e612a307b18e'
down_revision: Union[str, Sequence[str], None] = 'f16941095184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_category_weights_user_id_fkey'), 'user_category_weights', type_='foreignkey')
    op.create_foreign_key(None, 'user_category_weights', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_interactions_user_id_fkey'), 'user_interactions', type_='foreignkey')
    op.drop_constraint(op.f('user_interactions_news_id_fkey'), 'user_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'user_interactions', 'news', ['news_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_interactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_stats_user_id_fkey'), 'user_stats', type_='foreignkey')
    op.create_foreign_key(None, 'user_stats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stats', type_='foreignkey')
    op.create_foreign_key(op.f('user_stats_user_id_fkey'), 'user_stats', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_interactions', type_='foreignkey')
    op.drop_constraint(None, 'user_interactions', type_='foreignkey')
    op.create_foreign_key(op.f('user_interactions_news_id_fkey'), 'user_interactions', 'news', ['news_id'], ['id'])
    op.create_foreign_key(op.f('user_interactions_user_id_fkey'), 'user_interactions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_category_weights', type_='foreignkey')
    op.create_foreign_key(op.f('user_category_weights_user_id_fkey'), 'user_category_weights', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
