"""initial schema

Revision ID: f16941095184
Revises: 
Create Date: 2025-11-08 10:09:44.110355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16941095184'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('CLIMATE', 'CONFLICTS', 'CULTURE', 'ECONOMY', 'GLOSS', 'HEALTH', 'POLITICS', 'SCIENCE', 'SOCIETY', 'SPORTS', 'TRAVEL', name='newscategory'), nullable=False),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('total_shown', sa.Integer(), nullable=True),
    sa.Column('total_reactions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('max_id')
    )
    op.create_table('user_category_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('CLIMATE', 'CONFLICTS', 'CULTURE', 'ECONOMY', 'GLOSS', 'HEALTH', 'POLITICS', 'SCIENCE', 'SOCIETY', 'SPORTS', 'TRAVEL', name='newscategory'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('positive_reactions', sa.Integer(), nullable=True),
    sa.Column('negative_reactions', sa.Integer(), nullable=True),
    sa.Column('neutral_reactions', sa.Integer(), nullable=True),
    sa.Column('total_shown', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='unique_user_category')
    )
    op.create_table('user_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('news_title', sa.String(length=300), nullable=True),
    sa.Column('category', sa.Enum('CLIMATE', 'CONFLICTS', 'CULTURE', 'ECONOMY', 'GLOSS', 'HEALTH', 'POLITICS', 'SCIENCE', 'SOCIETY', 'SPORTS', 'TRAVEL', name='newscategory'), nullable=False),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('reaction', sa.Enum('LIKE', 'DISLIKE', 'SKIP', name='reactiontype'), nullable=False),
    sa.Column('reaction_time', sa.Integer(), nullable=True),
    sa.Column('shown_at', sa.DateTime(), nullable=True),
    sa.Column('reacted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_news_shown', sa.Integer(), nullable=True),
    sa.Column('total_reactions', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('total_likes', sa.Integer(), nullable=True),
    sa.Column('total_dislikes', sa.Integer(), nullable=True),
    sa.Column('total_skips', sa.Integer(), nullable=True),
    sa.Column('total_bookmarks', sa.Integer(), nullable=True),
    sa.Column('total_shares', sa.Integer(), nullable=True),
    sa.Column('avg_reaction_time', sa.Integer(), nullable=True),
    sa.Column('peak_activity_hour', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stats')
    op.drop_table('user_interactions')
    op.drop_table('user_category_weights')
    op.drop_table('users')
    op.drop_table('news')
    # ### end Alembic commands ###
